.github/workflows/pull-request-lint.yml, .github/workflows/test-cdk.yml
=> chore: add pr-lint workflow

docs/en/additional-resources.md
=> docs: fix broken link in page additional resources

docs/zh/deployment.md
=> feat: Feature/doc deployment

.github/workflows/eslint.yml
=> ci: update eslint job name

source/src/molecular-unfolding/cdk/utils/utils.ts, source/test/main.test.ts
closes #43
- Add `CrossEventRegionCondition` to `CreateEventRuleFuncServiceRoleXXXX`
=> fix: dependency issue

.github/workflows/test-python.yml, .gitignore, source/src/molecular-unfolding/pytest/test_sample.py
- setup pytest in the github workflow
=> feat: setup pytest

docs/mkdocs.base.yml, docs/mkdocs.en.yml, docs/mkdocs.zh.yml
=> docs: fix broken edit links

source/src/molecular-unfolding/cdk/utils/utils-batch.ts, source/src/molecular-unfolding/cdk/utils/utils.ts, source/test/benchmark.test.ts
*close #60 :*
add SSM permission to BatchEcsInstanceRole
=> fix: delete cloudformation issue [Cannot delete cloudformation due to role #60]

source/src/molecular-unfolding/molecular_unfolding.ipynb
2. solve the image display problem in the notebook
=> fix: update image reference in jupyter-notebook

source/src/molecular-unfolding/cdk/stack-main.ts
*close #80:*
change solution id.
=> feat: change sol id

docs/en/architecture.md, docs/zh/architecture.md
*close #65*
- refactor architecture doc
=> docs: enhance arch doc

docs/en/deployment.md
=> docs: fix typo and iam json syntax

.github/workflows/test-python.yml, docs/en/workshop/a-molecular-unfolding/batch-evaluation.md, docs/zh/workshop/a-molecular-unfolding/batch-evaluation.md, source/src/molecular-unfolding/batch-images/create-model/process.py, source/src/molecular-unfolding/lambda/TaskParametersLambda/app.py, source/src/molecular-unfolding/lambda/TaskParametersLambda/test_app.py
*close #37*
- Remove input parameters' range check for M/D
=> feat: remove input validation for M/D

docs/en/workshop/a-molecular-unfolding/evaluate-your-own-model.md, docs/zh/workshop/a-molecular-unfolding/evaluate-your-own-model.md
*close #86 , if available:*
doc update to add notice to change githubRepo
=> docs: add notice to change githubRepo

source/src/molecular-unfolding/cdk/construct-batch-evaluation.ts, source/src/molecular-unfolding/cdk/utils/utils.ts, source/test/benchmark.test.ts, source/test/listener.test.ts
*close #38*
add eventBridge to handle StepFunctions failure
=> feat: EventBridge to monitor StepFunctions Workflow failure

docs/en/deployment.md, docs/zh/deployment.md
update template to version v0.8.6
=> docs: update template to v0.8.6

README.md
Change README after aligning with global messages
=> docs: modify for blog message

.github/workflows/ghpage.yml, docs/en/deployment.md, docs/mkdocs.base.yml, docs/zh/deployment.md
=> docs: change cf version to v0.8.9

docs/en/workshop/a-molecular-unfolding/permissions.json, docs/zh/workshop/a-molecular-unfolding/permissions.json
=> docs: least permissions to deploy

source/src/molecular-unfolding/cdk/utils/custom-resource.ts, source/src/molecular-unfolding/cdk/utils/utils.ts
remove custom resource lambda concurrent
=> fix: rm custom resource lambda concurrent

source/src/molecular-unfolding/requirements.txt
fix package dependence in batch evaluation function
=> fix: fix batch package issue

source/src/molecular-unfolding/utility/ResultProcess.py
fix visualization problem for corner case molecule
=> fix: fix re rule for corner case

docs/en/workshop/a-molecular-unfolding/post-process.ipynb, source/src/molecular-unfolding/molecular_unfolding.ipynb, source/src/molecular-unfolding/utility/AnnealerOptimizer.py, source/src/molecular-unfolding/utility/ResultProcess.py
1. add more proficient method (neal sa) as the candidate for CC method
=> feat: add neal sa (c++) method support

source/src/molecular-unfolding/utility/AnnealerOptimizer.py, source/src/molecular-unfolding/utility/ResultProcess.py
add complete description for neal-sa method
=> feat: add complete method description for neal-sa

source/src/molecular-unfolding/batch-images/sa-optimizer/process.py
=> feat: integrate method neal-sa

source/package-lock.json, source/package.json, source/src/molecular-unfolding/cdk/resources/onStart.template, source/src/molecular-unfolding/lambda/DeviceAvailableCheckLambda/requirements.txt, source/src/molecular-unfolding/requirements.txt
=> chore: upgrade packages version to latest

docs/mkdocs.base.yml
=> docs: cloudFormation upgrade

docs/mkdocs.base.yml
=> chore: new cloudformation template

source/src/molecular-unfolding/lambda/AthenaTableLambda/app.py
=> fix: schema issue if table already exists

docs/mkdocs.base.yml
=> chore: upgrade cloudformation

README.md, docs/en/deployment.md, docs/mkdocs.base.yml, docs/zh/deployment.md
1. remove **Collection of Operational Metrics** section from readme
2. upgrade CloudFormation template 
3. add permissions message in deployment page
=> docs: remove Collection of Operational Metrics and others updates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, source/src/molecular-unfolding/cdk/utils/custom-resource.ts, source/test/main.test.ts
=> chore: add github template and fix name abbrev in test

docs/en/workshop/a-molecular-unfolding/permissions.json, docs/zh/workshop/a-molecular-unfolding/permissions.json
- add permission to access bucket `solutions*`
- remove permissions about `QR*`
=> docs: refine the deploy permissions

source/src/molecular-unfolding/lambda/TaskParametersLambda/app.py, source/src/molecular-unfolding/lambda/TaskParametersLambda/test_app.py
=> feat: remove model parameter check for D

CHANGELOG.md, README.md, source/README.md, source/src/molecular-unfolding/cdk/stack-main.ts
=> docs: update parameter description and change log

docs/en/cost.md, docs/zh/cost.md, source/src/molecular-unfolding/lambda/ParseBraketResultLambda/app.py, source/src/molecular-unfolding/lambda/TaskParametersLambda/app.py, source/src/molecular-unfolding/lambda/TaskParametersLambda/test_app.py
- add new device 'arn:aws:braket:us-west-2::device/qpu/d-wave/Advantage_system6'
- update cost of doc
=> feat: add new device Advantage_system6

docs/en/cost.md
=> docs:  update cost in doc

README.md
=> docs: add solution landing page

README.md
- add link to Github latest page in readme
=> docs: add link to Github latest page

README.md, docs/en/workshop/a-molecular-unfolding/batch-evaluation.md, docs/zh/workshop/a-molecular-unfolding/batch-evaluation.md
=> docs: add how to delete batch evaluation result  

docs/en/workshop/a-molecular-unfolding/batch-evaluation.md, docs/zh/workshop/a-molecular-unfolding/batch-evaluation.md
=> docs: fix format

docs/en/deployment.md, docs/en/workshop/permissions.json, docs/zh/deployment.md
=> docs: update permissions.json

source/src/notebook/healthcare-and-life-sciences/c-1-protein-folding-quantum-random-walk/requirements.txt
=> fix: fix requirements conflicts

source/src/notebook/healthcare-and-life-sciences/c-1-protein-folding-quantum-random-walk/requirements.txt, source/src/notebook/healthcare-and-life-sciences/d-1-retrosynthetic-planning-quantum-reinforcement-learning/retrosynthetic-planning-qrl.ipynb
=> fix: Fix code conflicts

source/src/notebook/healthcare-and-life-sciences/d-1-retrosynthetic-planning-quantum-reinforcement-learning/hybridjobs/retrorl_algorithm_script.py, source/src/notebook/healthcare-and-life-sciences/d-1-retrosynthetic-planning-quantum-reinforcement-learning/hybridjobs/utility/RetroRLAgent.py, source/src/notebook/healthcare-and-life-sciences/d-1-retrosynthetic-planning-quantum-reinforcement-learning/retrosynthetic-planning-qrl.ipynb
=> fix: fix retro notebook
